spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testR?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: root
#    password: test
#  sql:
#    init:
#      schema-locations: classpath:/db/schema.sql
#      data-locations: classpath:/db/data.sql
#      mode: always

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logical-delete-field: deleted
      id-type: auto
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.huaibei.entity